=== plaborie/cpoptimizer/miscellaneous/Miscellaneous/Reviews/Jury_Theses/2005-JulienBidot/sim/lib/msvc6/stat_mda/proto2/Release/sdxl.dtd
<!--
    This is the DTD for ILOG JViews Schedule Data Exchange Language.

    Version 5.5
-->

<!-- ISO date format -->
<!ENTITY % Datetime "CDATA">

<!ENTITY % Text "CDATA">

<!-- Must be an activity ID in the document -->
<!ENTITY % ActivityID "CDATA">

<!-- Must be an resource ID in the document -->
<!ENTITY % ResourceID "CDATA">

<!ENTITY % ConstraintType "(Start-Start|Start-End|End-Start|End-End)">

<!ELEMENT activity (activity|property)*>
<!ATTLIST activity
	id    ID         #REQUIRED
	name  %Text;     #REQUIRED
	start %Datetime; #REQUIRED
	end   %Datetime; #REQUIRED 
	info  %Text;     #IMPLIED >

<!ELEMENT activities (activity)+>
<!ATTLIST activities
	dateFormat %Text; #IMPLIED >

<!ELEMENT resource (resource|property)*>
<!ATTLIST resource
	id       ID     #REQUIRED
	name     %Text; #REQUIRED
	quantity %Text; #IMPLIED 
	info     %Text; #IMPLIED >

<!ELEMENT resources (resource)+>
<!ATTLIST resources>

<!ELEMENT reservation (property)*>
<!ATTLIST reservation
	activity %ActivityID; #REQUIRED
	resource %ResourceID; #REQUIRED 
	info     %Text;       #IMPLIED >

<!ELEMENT reservations (reservation)+>
<!ATTLIST reservations >

<!ELEMENT constraint (property)*>
<!ATTLIST constraint
	from %ActivityID;     #REQUIRED
	to   %ActivityID;     #REQUIRED 
	type %ConstraintType; #REQUIRED 
	info %Text;           #IMPLIED >

<!ELEMENT constraints (constraint)+>
<!ATTLIST constraints >

<!ELEMENT title (#PCDATA)>
<!ELEMENT desc (#PCDATA)>

<!ELEMENT schedule (title?, desc?, resources?, activities?,
    constraints?, reservations?) >
<!ATTLIST schedule 
        version %Text; #REQUIRED >

<!ELEMENT property (#PCDATA)>
<!ATTLIST property
	name       %Text;     #REQUIRED 
        javaClass  %Text;     #IMPLIED >

=== plaborie/cpoptimizer/miscellaneous/Miscellaneous/Reviews/Jury_Theses/2005-JulienBidot/sim/lib/msvc6/stat_mda/proto2/Release/solution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "sdxl.dtd">
<schedule version="3.5">
<desc>Scheduling Solution</desc>
  <resources>
    <resource id="All Resources" name="All Resources" quantity="10">
      <resource id="2" name="R0" quantity="1" />
      <resource id="4" name="R1" quantity="1" />
      <resource id="6" name="R2" quantity="1" />
      <resource id="8" name="R3" quantity="1" />
      <resource id="10" name="R4" quantity="1" />
      <resource id="12" name="R5" quantity="1" />
      <resource id="14" name="R6" quantity="1" />
      <resource id="16" name="R7" quantity="1" />
      <resource id="18" name="R8" quantity="1" />
      <resource id="20" name="R9" quantity="1" />
    </resource>
  </resources>
  <activities dateFormat="M-d-yyyy H:m:s">
    <activity id="All Activities" name="All Activities" start="1-1-2003 0:0:0" end="1-18-2003 12:57:17">
      <activity id="PP0" name="PP0" start="1-2-2003 12:37:4" end="1-18-2003 12:57:17">
        <activity id="24" name="PP0S9" start="1-18-2003 3:14:39" end="1-18-2003 12:57:17" />
        <activity id="27" name="PP0S8" start="1-17-2003 2:36:15" end="1-17-2003 12:24:1" />
        <activity id="31" name="PP0S7" start="1-15-2003 23:39:15" end="1-16-2003 16:47:12" />
        <activity id="35" name="PP0S6" start="1-15-2003 4:24:15" end="1-15-2003 18:3:1" />
        <activity id="39" name="PP0S5" start="1-9-2003 8:38:57" end="1-10-2003 21:45:32" />
        <activity id="43" name="PP0S4" start="1-6-2003 22:27:0" end="1-7-2003 8:46:51" />
        <activity id="47" name="PP0S3" start="1-6-2003 11:53:2" end="1-6-2003 22:27:0" />
        <activity id="51" name="PP0S2" start="1-5-2003 20:43:9" end="1-6-2003 5:35:44" />
        <activity id="55" name="PP0S1" start="1-3-2003 13:48:50" end="1-3-2003 22:40:8" />
        <activity id="59" name="PP0S0" start="1-2-2003 12:37:4" end="1-3-2003 13:25:44" />
        <activity id="954" name="PP0DueDate" start="1-11-2003 5:18:33" end="1-11-2003 5:18:33" />
      </activity>
      <activity id="PP1" name="PP1" start="1-1-2003 8:11:31" end="1-18-2003 9:21:41">
        <activity id="63" name="PP1S9" start="1-17-2003 18:1:32" end="1-18-2003 9:21:41" />
        <activity id="66" name="PP1S8" start="1-17-2003 10:16:58" end="1-17-2003 18:1:32" />
        <activity id="70" name="PP1S7" start="1-16-2003 17:11:35" end="1-17-2003 8:7:21" />
        <activity id="74" name="PP1S6" start="1-15-2003 16:15:13" end="1-16-2003 4:43:24" />
        <activity id="78" name="PP1S5" start="1-13-2003 8:41:7" end="1-14-2003 0:5:7" />
        <activity id="82" name="PP1S4" start="1-12-2003 23:13:53" end="1-13-2003 8:41:7" />
        <activity id="86" name="PP1S3" start="1-12-2003 5:31:17" end="1-12-2003 13:32:32" />
        <activity id="90" name="PP1S2" start="1-5-2003 7:57:0" end="1-5-2003 18:6:35" />
        <activity id="94" name="PP1S1" start="1-4-2003 18:58:1" end="1-5-2003 5:34:33" />
        <activity id="98" name="PP1S0" start="1-1-2003 8:11:31" end="1-1-2003 22:19:48" />
        <activity id="956" name="PP1DueDate" start="1-9-2003 3:23:15" end="1-9-2003 3:23:15" />
      </activity>
      <activity id="PP2" name="PP2" start="1-1-2003 19:20:8" end="1-13-2003 9:54:16">
        <activity id="102" name="PP2S9" start="1-13-2003 0:38:35" end="1-13-2003 9:54:16" />
        <activity id="105" name="PP2S8" start="1-12-2003 2:17:30" end="1-12-2003 15:44:43" />
        <activity id="109" name="PP2S7" start="1-11-2003 5:42:56" end="1-11-2003 16:52:50" />
        <activity id="113" name="PP2S6" start="1-8-2003 8:44:11" end="1-9-2003 0:45:24" />
        <activity id="117" name="PP2S5" start="1-7-2003 19:36:13" end="1-8-2003 8:44:11" />
        <activity id="121" name="PP2S4" start="1-6-2003 16:45:38" end="1-7-2003 4:9:39" />
        <activity id="125" name="PP2S3" start="1-5-2003 23:4:19" end="1-6-2003 16:45:38" />
        <activity id="129" name="PP2S2" start="1-5-2003 2:40:1" end="1-5-2003 17:56:19" />
        <activity id="133" name="PP2S1" start="1-4-2003 4:45:53" end="1-4-2003 15:28:50" />
        <activity id="137" name="PP2S0" start="1-1-2003 19:20:8" end="1-2-2003 6:49:17" />
        <activity id="958" name="PP2DueDate" start="1-6-2003 15:29:55" end="1-6-2003 15:29:55" />
      </activity>
      <activity id="PP3" name="PP3" start="1-1-2003 0:0:0" end="1-13-2003 5:2:57">
        <activity id="141" name="PP3S9" start="1-12-2003 17:5:34" end="1-13-2003 5:2:57" />
        <activity id="144" name="PP3S8" start="1-12-2003 5:31:17" end="1-12-2003 17:5:34" />
        <activity id="148" name="PP3S7" start="1-11-2003 19:1:10" end="1-12-2003 5:31:17" />
        <activity id="152" name="PP3S6" start="1-9-2003 23:25:44" end="1-10-2003 10:8:41" />
        <activity id="156" name="PP3S5" start="1-8-2003 20:37:43" end="1-9-2003 7:29:39" />
        <activity id="160" name="PP3S4" start="1-7-2003 4:1:57" end="1-7-2003 20:17:17" />
        <activity id="164" name="PP3S3" start="1-6-2003 18:48:50" end="1-7-2003 4:1:57" />
        <activity id="168" name="PP3S2" start="1-5-2003 5:34:33" end="1-5-2003 18:10:26" />
        <activity id="172" name="PP3S1" start="1-2-2003 8:57:37" end="1-3-2003 19:49:27" />
        <activity id="176" name="PP3S0" start="1-1-2003 0:0:0" end="1-2-2003 8:57:37" />
        <activity id="960" name="PP3DueDate" start="1-8-2003 7:22:3" end="1-8-2003 7:22:3" />
      </activity>
      <activity id="PP4" name="PP4" start="1-1-2003 0:0:0" end="1-12-2003 9:14:35">
        <activity id="180" name="PP4S9" start="1-11-2003 20:43:50" end="1-12-2003 9:14:35" />
        <activity id="183" name="PP4S8" start="1-9-2003 0:45:24" end="1-9-2003 11:52:44" />
        <activity id="187" name="PP4S7" start="1-7-2003 23:59:18" end="1-8-2003 9:52:12" />
        <activity id="191" name="PP4S6" start="1-7-2003 12:13:28" end="1-7-2003 23:59:18" />
        <activity id="195" name="PP4S5" start="1-6-2003 12:3:18" end="1-7-2003 0:59:43" />
        <activity id="199" name="PP4S4" start="1-4-2003 23:58:19" end="1-5-2003 14:4:2" />
        <activity id="203" name="PP4S3" start="1-4-2003 15:28:50" end="1-4-2003 23:58:19" />
        <activity id="207" name="PP4S2" start="1-3-2003 22:17:2" end="1-4-2003 7:1:55" />
        <activity id="211" name="PP4S1" start="1-1-2003 10:53:13" end="1-1-2003 23:14:59" />
        <activity id="215" name="PP4S0" start="1-1-2003 0:0:0" end="1-1-2003 10:19:51" />
        <activity id="962" name="PP4DueDate" start="1-7-2003 15:1:35" end="1-7-2003 15:1:35" />
      </activity>
      <activity id="PP5" name="PP5" start="1-1-2003 0:0:0" end="1-16-2003 13:52:40">
        <activity id="219" name="PP5S9" start="1-16-2003 4:43:24" end="1-16-2003 13:52:40" />
        <activity id="222" name="PP5S8" start="1-13-2003 18:59:41" end="1-15-2003 0:29:24" />
        <activity id="226" name="PP5S7" start="1-13-2003 8:41:7" end="1-13-2003 18:59:41" />
        <activity id="230" name="PP5S6" start="1-9-2003 0:15:53" end="1-10-2003 18:4:48" />
        <activity id="234" name="PP5S5" start="1-8-2003 8:24:56" end="1-8-2003 20:36:26" />
        <activity id="238" name="PP5S4" start="1-7-2003 22:30:45" end="1-8-2003 8:24:56" />
        <activity id="242" name="PP5S3" start="1-7-2003 12:13:28" end="1-7-2003 22:30:45" />
        <activity id="246" name="PP5S2" start="1-6-2003 19:56:51" end="1-7-2003 12:13:28" />
        <activity id="250" name="PP5S1" start="1-6-2003 3:40:14" end="1-6-2003 12:3:18" />
        <activity id="254" name="PP5S0" start="1-1-2003 0:0:0" end="1-1-2003 16:19:11" />
        <activity id="964" name="PP5DueDate" start="1-9-2003 20:5:32" end="1-9-2003 20:5:32" />
      </activity>
      <activity id="PP6" name="PP6" start="1-1-2003 12:57:42" end="1-16-2003 17:11:35">
        <activity id="258" name="PP6S9" start="1-16-2003 4:39:33" end="1-16-2003 17:11:35" />
        <activity id="261" name="PP6S8" start="1-15-2003 14:9:27" end="1-16-2003 4:39:33" />
        <activity id="265" name="PP6S7" start="1-15-2003 0:29:24" end="1-15-2003 14:9:27" />
        <activity id="269" name="PP6S6" start="1-14-2003 6:37:49" end="1-14-2003 15:27:50" />
        <activity id="273" name="PP6S5" start="1-12-2003 23:13:53" end="1-13-2003 17:47:49" />
        <activity id="277" name="PP6S4" start="1-12-2003 10:58:32" end="1-12-2003 23:13:53" />
        <activity id="281" name="PP6S3" start="1-5-2003 23:21:0" end="1-6-2003 9:7:29" />
        <activity id="285" name="PP6S2" start="1-5-2003 11:30:2" end="1-5-2003 20:44:26" />
        <activity id="289" name="PP6S1" start="1-4-2003 8:56:8" end="1-4-2003 22:52:52" />
        <activity id="293" name="PP6S0" start="1-1-2003 12:57:42" end="1-3-2003 0:7:30" />
        <activity id="966" name="PP6DueDate" start="1-6-2003 18:27:1" end="1-6-2003 18:27:1" />
      </activity>
      <activity id="PP7" name="PP7" start="1-3-2003 3:23:51" end="1-12-2003 4:11:43">
        <activity id="297" name="PP7S9" start="1-11-2003 18:34:13" end="1-12-2003 4:11:43" />
        <activity id="300" name="PP7S8" start="1-11-2003 6:56:5" end="1-11-2003 15:20:26" />
        <activity id="304" name="PP7S7" start="1-10-2003 10:8:41" end="1-10-2003 23:19:13" />
        <activity id="308" name="PP7S6" start="1-9-2003 11:52:44" end="1-9-2003 22:43:23" />
        <activity id="312" name="PP7S5" start="1-7-2003 23:59:18" end="1-8-2003 14:3:44" />
        <activity id="316" name="PP7S4" start="1-6-2003 3:40:14" end="1-6-2003 18:48:50" />
        <activity id="320" name="PP7S3" start="1-5-2003 18:10:26" end="1-6-2003 3:40:14" />
        <activity id="324" name="PP7S2" start="1-5-2003 0:27:50" end="1-5-2003 10:20:44" />
        <activity id="328" name="PP7S1" start="1-4-2003 8:56:8" end="1-5-2003 0:27:50" />
        <activity id="332" name="PP7S0" start="1-3-2003 3:23:51" end="1-4-2003 8:56:8" />
        <activity id="968" name="PP7DueDate" start="1-7-2003 9:24:4" end="1-7-2003 9:24:4" />
      </activity>
